[package]
name = "mui-misskey-websocket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.44.0"

tokio = {version="1.37.0", features=["full"]}
websocket = "0.27.1"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
reqwest = "0.12.4"

